
name: Docker Image Build and Push to Dockerhub - CI/CD

on: 
  push:
    branches: 
      - release

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set Tag in evn variable
      run: echo $(git log -1 --pretty=%H)
      env:
       TAG: 3.1
      
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USER }}/${{ secrets.REPOSITORY_NAME }}:$(git log -1 --pretty=%H)
      
    - name: Docker Login
      run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
      
    - name: Image push
      run: docker push ${{ secrets.DOCKER_USER }}/${{ secrets.REPOSITORY_NAME }}:$(date +%F)
