
name: Docker Image Build and Push to Dockerhub - CI/CD

on: 
  push:
    branches: 
      - master

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
#     - name: Set Tag in evn variable
#       run: echo ${TAG}
#       env:
#         TAG: 3.1
      
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USER }}/${{ REPOSITORY_NAME }}:$(date +%F)
      
    - name: Docker Login
      run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
      
    - name: Image push
      run: docker push ${{ secrets.DOCKER_USER }}/${{ REPOSITORY_NAME }}:$(date +%F)
